### PR TITLE
asyncTrial builder

### PR DESCRIPTION
**Pull request by ghost**
specialized builder as  suggested in #10

### CODE REVIEW

**Comment by tpetricek** [comment]
The implementation looks good to me!

Although the project is not heavy on documentation yet, this builder is one of the things that would deserve to be documented. Fancy adding an F# script file with a few comments to demonstrate the feature :-)?

**Comment by forki** [comment]
please move the stuff into ErrorHandling.fs. otherwise it's hard to do single file Paket linking (and that's the whole point of that lib)

**Comment by forki** [comment]
OK I move it, but it's still lacking docs and tests.

**Comment by ghost** [comment]
I just wanted to be sure the builder is ok in principle. I will provide docs and tests sometime this week :-)

**Pull request merged**
