### PR TITLE
Added an extension method for C# to convert an FSharpOption into a Result

### PR DESCRIPTION
**Pull request by battermann**

### CODE REVIEW

**Comment by forki** [comment]
Did you look at the build error?

**Comment by battermann** [comment]
I don't know how to retrieve detailed information about the error from appveyor.

It builds correctly on my machine from VS and script. All tests pass.

Can you help me out?

**Comment by forki** [comment]
Looks like it refused to build. Please rebase and push again

**Comment by battermann** [comment]
Oh, my repo was outdated... sorry my fault!

**Pull request merged**
